# Imports & setup

In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import pandas as pd
import numpy as np
import pickle
from xgboost import XGBRegressor

In [3]:
features = ['Was_home',
 'Rating_difference',
 'Min_2',
 'Gls_2',
 'Ast_2',
 'xG_2',
 'xA_2',
 'Team_CS_2',
 'Team_score_2',
 'Opp_score_2',
 'Team_result_2',
 'FPL_points_2',
 'Min_4',
 'Gls_4',
 'Ast_4',
 'xG_4',
 'xA_4',
 'Team_CS_4',
 'Team_score_4',
 'Opp_score_4',
 'Team_result_4',
 'FPL_points_4',
 'Min_30',
 'Gls_30',
 'Ast_30',
 'xG_30',
 'xA_30',
 'Team_CS_30',
 'Team_score_30',
 'Opp_score_30',
 'Team_result_30',
 'FPL_points_30',
 'DEF',
 'FWD',
 'MID']

info = ["Name_original", "GW", "Season", "Team", "Opponent", "Was_home", "Team_rating", "Opp_rating", "FPL_pos", "Price"]
to_predict = ["FPL_points"]

In [4]:
len(features)

35

# Reading from files

In [5]:
df = pd.read_csv("data/upcoming/upcoming_fixtures.csv")
CURRENT_SEASON = "2023-24"

In [6]:
# df = df[df["GW"] == 2]

In [7]:
# X_test = df[df["Season"] == CURRENT_SEASON][features]
X_test = df[df["Season"] == CURRENT_SEASON]
# .reset_index(drop=True)

In [8]:
# X_test[X_test["FPL_pos"] == "MID"]["Gls_4"].unique()

In [9]:
df.columns

Index(['Unnamed: 0', 'Ast_2', 'Ast_30', 'Ast_4', 'DEF', 'FPL_points',
       'FPL_points_2', 'FPL_points_30', 'FPL_points_4', 'FPL_pos', 'FWD', 'GW',
       'Gls_2', 'Gls_30', 'Gls_4', 'MID', 'Min_2', 'Min_30', 'Min_4',
       'Name_original', 'Opp_rating', 'Opp_score_2', 'Opp_score_30',
       'Opp_score_4', 'Opponent', 'Rating_difference', 'Season', 'Team',
       'Team_CS_2', 'Team_CS_30', 'Team_CS_4', 'Team_rating', 'Team_result_2',
       'Team_result_30', 'Team_result_4', 'Team_score_2', 'Team_score_30',
       'Team_score_4', 'Was_home', 'xA_2', 'xA_30', 'xA_4', 'xG_2', 'xG_30',
       'xG_4', 'xP', 'Finished', 'Date', 'Price'],
      dtype='object')

In [10]:
class PositionalModel:
    def __init__(self,  model_GK=None, model_DEF=None, model_MID=None, model_FWD=None):
        if model_GK:
            self.model_GK = model_GK
        else:
            self.model_GK = XGBRegressor(random_state=42, verbosity = 0,
            # n_estimators=500,
            # early_stopping_rounds=5,
            # learning_rate=0.2
            )
        
        if model_DEF:
            self.model_DEF = model_DEF
        else:
            self.model_DEF = XGBRegressor(random_state=42, verbosity = 0,
            n_estimators=500,
            early_stopping_rounds=5,
            learning_rate=0.2
            )
        
        if model_MID:
            self.model_MID = model_MID
        else:
            self.model_MID = XGBRegressor(random_state=42, verbosity = 0,
            n_estimators=500,
            early_stopping_rounds=5,
            learning_rate=0.2
            )
        
        if model_FWD:
            self.model_FWD = model_FWD
        else:
            self.model_FWD = XGBRegressor(random_state=42, verbosity = 0,
            n_estimators=500,
            early_stopping_rounds=5,
            learning_rate=0.2
            )
        
        
    def fit(self, X, y, X_valid, y_valid):
        # print(y[y["FPL_pos"] == "GK"].shape)
        self.model_GK.fit(X[X["FPL_pos"] == "GK"][features], y[y["FPL_pos"] == "GK"][to_predict],
        # eval_set=[(X_valid[X_valid["FPL_pos"] == "GK"][features], y_valid[y_valid["FPL_pos"] == "GK"][to_predict])],
        verbose=False)
        self.model_DEF.fit(X[X["FPL_pos"] == "DEF"][features], y[y["FPL_pos"] == "DEF"][to_predict],
        eval_set=[(X_valid[X_valid["FPL_pos"] == "DEF"][features], y_valid[y_valid["FPL_pos"] == "DEF"][to_predict])],
        verbose=False)
        self.model_MID.fit(X[X["FPL_pos"] == "MID"][features], y[y["FPL_pos"] == "MID"][to_predict],
        eval_set=[(X_valid[X_valid["FPL_pos"] == "MID"][features], y_valid[y_valid["FPL_pos"] == "MID"][to_predict])],
        verbose=False)
        self.model_FWD.fit(X[X["FPL_pos"] == "FWD"][features], y[y["FPL_pos"] == "FWD"][to_predict],
        eval_set=[(X_valid[X_valid["FPL_pos"] == "FWD"][features], y_valid[y_valid["FPL_pos"] == "FWD"][to_predict])],
        verbose=False)
        
    def predict(self, X):
        output = []
        i = 0
        for ind, row in X.iterrows():
            # print(i, row["Name_original"], row["FPL_points_4"], X.head(i+1).tail(1)["FPL_points_4"])
            if row["FPL_pos"] == "GK":
                # print(row["FPL_pos"])
                output.append( self.model_GK.predict( X.head(i+1).tail(1)[features] ) )
            if row["FPL_pos"] == "DEF":
                # print(row["FPL_pos"])
                output.append( self.model_DEF.predict( X.head(i+1).tail(1)[features] ) )
            if row["FPL_pos"] == "MID":
                # print(row["FPL_pos"])
                output.append( self.model_MID.predict( X.head(i+1).tail(1)[features] ) )
            if row["FPL_pos"] == "FWD":
                # print(row["FPL_pos"])
                output.append( self.model_FWD.predict( X.head(i+1).tail(1)[features] ) )
            i += 1
        return np.array(output).flatten()

In [11]:
file1 = open("models/GBR_GK.pkl",'rb')
file2 = open("models/GBR_DEF.pkl",'rb')
file3 = open("models/GBR_MID.pkl",'rb')
file4 = open("models/GBR_FWD.pkl",'rb')

model_GK = pickle.load(file1)
model_DEF = pickle.load(file2)
model_MID = pickle.load(file3)
model_FWD = pickle.load(file4)

model = PositionalModel(model_GK, model_DEF, model_MID, model_FWD)

In [12]:
model

In [13]:
model_MID.predict( X_test.head(10)[features] )

array([1.1904162, 1.1904162, 1.1904162, 0.6569128, 0.6569128, 1.1904162,
       1.1904162, 0.6569128, 0.6569128, 1.1904162], dtype=float32)

In [14]:
model_MID.predict( X_test.head(12)[features] )

array([1.1904162, 1.1904162, 1.1904162, 0.6569128, 0.6569128, 1.1904162,
       1.1904162, 0.6569128, 0.6569128, 1.1904162, 1.1904162, 1.1904162],
      dtype=float32)

In [15]:
model.predict( X_test.head(5) )

array([4.588393  , 3.9490452 , 4.588393  , 0.76540446, 0.5811391 ],
      dtype=float32)

In [16]:
model.predict( X_test.head(3) )

array([4.588393 , 3.9490452, 4.588393 ], dtype=float32)

In [17]:
model.predict( X_test.head(4) )

array([4.588393  , 3.9490452 , 4.588393  , 0.76540446], dtype=float32)

In [18]:
X_test.head(5)

Unnamed: 0  Ast_2  Ast_30  Ast_4  DEF  FPL_points  FPL_points_2  \
15408        1691    0.0     0.0    0.0  0.0         NaN           0.5   
15409        1669    0.0     0.0    0.0  0.0         NaN           0.5   
15410        1692    0.0     0.0    0.0  0.0         NaN           0.5   
15411        1693    0.0     0.0    0.0  0.0         NaN           0.5   
15412        1670    0.0     0.0    0.0  0.0         NaN           0.5   

       FPL_points_30  FPL_points_4 FPL_pos  ...  xA_2   xA_30   xA_4  xG_2  \
15408       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15409       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15410       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15411       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15412       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   

        xG_30  xG_4  xP  Finished        Date Price  
15408  0.0375   0.0 NaN     False  2023-08-12  45.0  
15409  0.0375   0.0 NaN     False  2023-08-19  45.0  
15410  0.0375   0.0 NaN     False  2023-08-26  45.0  
15411  0.0375   0.0 NaN     False  2023-09-02  45.0  
15412  0.0375   0.0 NaN     False  2023-09-16  45.0  

[5 rows x 49 columns]

In [19]:
X_test.head(3)

Unnamed: 0  Ast_2  Ast_30  Ast_4  DEF  FPL_points  FPL_points_2  \
15408        1691    0.0     0.0    0.0  0.0         NaN           0.5   
15409        1669    0.0     0.0    0.0  0.0         NaN           0.5   
15410        1692    0.0     0.0    0.0  0.0         NaN           0.5   

       FPL_points_30  FPL_points_4 FPL_pos  ...  xA_2   xA_30   xA_4  xG_2  \
15408       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15409       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   
15410       0.428571      0.333333     FWD  ...  0.05  0.0125  0.025   0.0   

        xG_30  xG_4  xP  Finished        Date Price  
15408  0.0375   0.0 NaN     False  2023-08-12  45.0  
15409  0.0375   0.0 NaN     False  2023-08-19  45.0  
15410  0.0375   0.0 NaN     False  2023-08-26  45.0  

[3 rows x 49 columns]

In [20]:
X_test.head(3)[features]

Was_home  Rating_difference  Min_2  Gls_2  Ast_2  xG_2  xA_2  \
15408       1.0         221.646484   18.0    0.0    0.0   0.0  0.05   
15409       0.0         116.732910   18.0    0.0    0.0   0.0  0.05   
15410       1.0          54.812988   18.0    0.0    0.0   0.0  0.05   

       Team_CS_2  Team_score_2  Opp_score_2  ...   xG_30   xA_30  Team_CS_30  \
15408        0.0           1.0          2.5  ...  0.0375  0.0125       0.375   
15409        0.0           1.0          2.5  ...  0.0375  0.0125       0.375   
15410        0.0           1.0          2.5  ...  0.0375  0.0125       0.375   

       Team_score_30  Opp_score_30  Team_result_30  FPL_points_30  DEF  FWD  \
15408          0.875         1.125            1.25       0.428571  0.0  1.0   
15409          0.875         1.125            1.25       0.428571  0.0  1.0   
15410          0.875         1.125            1.25       0.428571  0.0  1.0   

       MID  
15408  0.0  
15409  0.0  
15410  0.0  

[3 rows x 35 columns]

# Predicting

In [21]:
def adjust_for_injuries(df):
    active_players = pd.read_csv("data/misc/active_players.csv")
    injured_players = active_players[active_players["chance_of_playing_this_round"] == 0]["name"].to_list()
    df.loc[df["Name_original"].isin(injured_players),"Pred"] = 0
    return df

In [22]:
def get_predictions(model, df, X):
    # make predictions on the test data and glues them to the rest of the dataframe
    predictions = model.predict(X)
    
    df_predictions = df[(df["Season"] == CURRENT_SEASON)].reset_index(drop=True)
        
    print(len(predictions), df_predictions.shape)
        
    df_predictions.loc[:, "Pred"] = predictions
    preds = df_predictions[info + ["Pred"]]
    
    preds = adjust_for_injuries(preds).sort_values(by=["Pred"], ascending = False)
    
    return preds

In [23]:
X_test

Unnamed: 0  Ast_2    Ast_30  Ast_4  DEF  FPL_points  FPL_points_2  \
15408        1691    0.0  0.000000    0.0  0.0         NaN           0.5   
15409        1669    0.0  0.000000    0.0  0.0         NaN           0.5   
15410        1692    0.0  0.000000    0.0  0.0         NaN           0.5   
15411        1693    0.0  0.000000    0.0  0.0         NaN           0.5   
15412        1670    0.0  0.000000    0.0  0.0         NaN           0.5   
...           ...    ...       ...    ...  ...         ...           ...   
28920        6132    0.0  0.033333    0.0  0.0         NaN           1.0   
28921        6133    0.0  0.033333    0.0  0.0         NaN           1.0   
28922        6126    0.0  0.033333    0.0  0.0         NaN           1.0   
28923        6134    0.0  0.033333    0.0  0.0         NaN           1.0   
28924        6127    0.0  0.033333    0.0  0.0         NaN           1.0   

       FPL_points_30  FPL_points_4 FPL_pos  ...          xA_2   xA_30  \
15408       0.428571      0.333333     FWD  ...  5.000000e-02  0.0125   
15409       0.428571      0.333333     FWD  ...  5.000000e-02  0.0125   
15410       0.428571      0.333333     FWD  ...  5.000000e-02  0.0125   
15411       0.428571      0.333333     FWD  ...  5.000000e-02  0.0125   
15412       0.428571      0.333333     FWD  ...  5.000000e-02  0.0125   
...              ...           ...     ...  ...           ...     ...   
28920       1.733333      0.750000     MID  ...  2.137179e-15  0.0200   
28921       1.733333      0.750000     MID  ...  2.137179e-15  0.0200   
28922       1.733333      0.750000     MID  ...  2.137179e-15  0.0200   
28923       1.733333      0.750000     MID  ...  2.137179e-15  0.0200   
28924       1.733333      0.750000     MID  ...  2.137179e-15  0.0200   

               xA_4          xG_2     xG_30          xG_4  xP  Finished  \
15408  2.500000e-02  0.000000e+00  0.037500  0.000000e+00 NaN     False   
15409  2.500000e-02  0.000000e+00  0.037500  0.000000e+00 NaN     False   
15410  2.500000e-02  0.000000e+00  0.037500  0.000000e+00 NaN     False   
15411  2.500000e-02  0.000000e+00  0.037500  0.000000e+00 NaN     False   
15412  2.500000e-02  0.000000e+00  0.037500  0.000000e+00 NaN     False   
...             ...           ...       ...           ...  ..       ...   
28920  4.718448e-16  1.554312e-15  0.006667  6.383782e-16 NaN     False   
28921  4.718448e-16  1.554312e-15  0.006667  6.383782e-16 NaN     False   
28922  4.718448e-16  1.554312e-15  0.006667  6.383782e-16 NaN     False   
28923  4.718448e-16  1.554312e-15  0.006667  6.383782e-16 NaN     False   
28924  4.718448e-16  1.554312e-15  0.006667  6.383782e-16 NaN     False   

             Date Price  
15408  2023-08-12  45.0  
15409  2023-08-19  45.0  
15410  2023-08-26  45.0  
15411  2023-09-02  45.0  
15412  2023-09-16  45.0  
...           ...   ...  
28920  2024-04-20  50.0  
28921  2024-04-27  50.0  
28922  2024-05-04  50.0  
28923  2024-05-11  50.0  
28924  2024-05-19  50.0  

[13517 rows x 49 columns]

In [24]:
%%time
preds = get_predictions(model, df, X_test)

13517 (13517, 49)
CPU times: total: 2min 42s
Wall time: 52.5 s


C:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [25]:
# preds[(preds["FPL_pos"] == "GK") & (preds["GW"] == 2)].head(30)

In [26]:
# next gameweek
preds[preds["GW"] == 3].head(50)

Name_original   GW   Season             Team  \
1708                   Bryan Mbeumo  3.0  2023-24        Brentford   
2880                  Danny Welbeck  3.0  2023-24         Brighton   
875                 Anthony Martial  3.0  2023-24   Manchester Utd   
4284                Folarin Balogun  3.0  2023-24          Arsenal   
7086                    Kai Havertz  3.0  2023-24          Arsenal   
7011                   Julio Enciso  3.0  2023-24         Brighton   
3222        Diogo Teixeira da Silva  3.0  2023-24        Liverpool   
7049                 Julián Álvarez  3.0  2023-24  Manchester City   
3526                  Eddie Nketiah  3.0  2023-24          Arsenal   
4056                  Evan Ferguson  3.0  2023-24         Brighton   
10263                 Ollie Watkins  3.0  2023-24      Aston Villa   
11060        Richarlison de Andrade  3.0  2023-24        Tottenham   
8673                Marcus Rashford  3.0  2023-24   Manchester Utd   
1632         Bruno Borges Fernandes  3.0  2023-24   Manchester Utd   
989       Antony Matheus dos Santos  3.0  2023-24   Manchester Utd   
10794               Raheem Sterling  3.0  2023-24          Chelsea   
4473       Gabriel Martinelli Silva  3.0  2023-24          Arsenal   
1821                  Callum Wilson  3.0  2023-24    Newcastle Utd   
10453                   Pascal Groß  3.0  2023-24         Brighton   
9467                  Mohamed Salah  3.0  2023-24        Liverpool   
647                     Andi Zeqiri  3.0  2023-24         Brighton   
8787                Martin Ødegaard  3.0  2023-24          Arsenal   
7802               Leandro Trossard  3.0  2023-24          Arsenal   
12040                   Solly March  3.0  2023-24         Brighton   
1102                   Ben Chilwell  3.0  2023-24          Chelsea   
4511   Gabriel dos Santos Magalhães  3.0  2023-24          Arsenal   
1291                 Benjamin White  3.0  2023-24          Arsenal   
2049                  Charlie Goode  3.0  2023-24        Brentford   
3944                 Erling Haaland  3.0  2023-24  Manchester City   
10946                   Reece James  3.0  2023-24          Chelsea   
7161                   Kaoru Mitoma  3.0  2023-24         Brighton   
9164                     Max Kilman  3.0  2023-24           Wolves   
7312                Kevin De Bruyne  3.0  2023-24  Manchester City   
13406                   Yoane Wissa  3.0  2023-24        Brentford   
13217                William Saliba  3.0  2023-24          Arsenal   
12078                 Son Heung-min  3.0  2023-24        Tottenham   
1254                        Ben Mee  3.0  2023-24        Brentford   
12724            Toti António Gomes  3.0  2023-24           Wolves   
2614                Cristian Romero  3.0  2023-24        Tottenham   
8068              Lisandro Martínez  3.0  2023-24   Manchester Utd   
2576                   Craig Dawson  3.0  2023-24           Wolves   
115               Aaron Wan-Bissaka  3.0  2023-24   Manchester Utd   
7689                     Kurt Zouma  3.0  2023-24         West Ham   
10605              Pervis Estupiñán  3.0  2023-24         Brighton   
11098                    Rico Henry  3.0  2023-24        Brentford   
10187           Oleksandr Zinchenko  3.0  2023-24          Arsenal   
5382                   Jadon Sancho  3.0  2023-24   Manchester Utd   
12762        Trent Alexander-Arnold  3.0  2023-24        Liverpool   
6634           Jonathan Castro Otto  3.0  2023-24           Wolves   
4019                  Ethan Pinnock  3.0  2023-24        Brentford   

               Opponent  Was_home  Team_rating   Opp_rating FPL_pos  Price  \
1708     Crystal Palace       1.0  1822.547119  1763.994995     FWD   65.0   
2880           West Ham       1.0  1832.364258  1777.551270     FWD   60.0   
875     Nott'ham Forest       1.0  1877.037842  1671.868774     FWD   65.0   
4284             Fulham       1.0  1921.462769  1745.365723     FWD   45.0   
7086             Fulham       1.0  1921.462769  1745.365723  

In [27]:
# all preds
preds.head(20)

Name_original    GW   Season             Team  \
9323           Michail Antonio  10.0  2023-24         West Ham   
9325           Michail Antonio  12.0  2023-24         West Ham   
9346           Michail Antonio  33.0  2023-24         West Ham   
9320           Michail Antonio   7.0  2023-24         West Ham   
9335           Michail Antonio  22.0  2023-24         West Ham   
9327           Michail Antonio  14.0  2023-24         West Ham   
9330           Michail Antonio  17.0  2023-24         West Ham   
9350           Michail Antonio  37.0  2023-24         West Ham   
9341           Michail Antonio  28.0  2023-24         West Ham   
12267            Taiwo Awoniyi   2.0  2023-24  Nott'ham Forest   
12283            Taiwo Awoniyi  18.0  2023-24  Nott'ham Forest   
12274            Taiwo Awoniyi   9.0  2023-24  Nott'ham Forest   
3221   Diogo Teixeira da Silva   2.0  2023-24        Liverpool   
3257   Diogo Teixeira da Silva  38.0  2023-24        Liverpool   
3255   Diogo Teixeira da Silva  36.0  2023-24        Liverpool   
3252   Diogo Teixeira da Silva  33.0  2023-24        Liverpool   
3236   Diogo Teixeira da Silva  17.0  2023-24        Liverpool   
3250   Diogo Teixeira da Silva  31.0  2023-24        Liverpool   
3249   Diogo Teixeira da Silva  30.0  2023-24        Liverpool   
3225   Diogo Teixeira da Silva   6.0  2023-24        Liverpool   

               Opponent  Was_home  Team_rating   Opp_rating FPL_pos  Price  \
9323            Everton       1.0  1777.551270  1699.505859     FWD   60.0   
9325    Nott'ham Forest       1.0  1777.551270  1671.868774     FWD   60.0   
9346             Fulham       1.0  1777.551270  1745.365723     FWD   60.0   
9320   Sheffield United       1.0  1777.551270  1637.473755     FWD   60.0   
9335        Bournemouth       1.0  1777.551270  1662.536621     FWD   60.0   
9327     Crystal Palace       1.0  1777.551270  1763.994995     FWD   60.0   
9330             Wolves       1.0  1777.551270  1715.631348     FWD   60.0   
9350              Luton       1.0  1777.551270  1602.327637     FWD   60.0   
9341            Burnley       1.0  1777.551270  1722.802979     FWD   60.0   
12267  Sheffield United       1.0  1671.868774  1637.473755     FWD   65.0   
12283       Bournemouth       1.0  1671.868774  1662.536621     FWD   65.0   
12274             Luton       1.0  1671.868774  1602.327637     FWD   65.0   
3221        Bournemouth       1.0  1943.976074  1662.536621     FWD   80.0   
3257             Wolves       1.0  1943.976074  1715.631348     FWD   80.0   
3255          Tottenham       1.0  1943.976074  1817.656738     FWD   80.0   
3252     Crystal Palace       1.0  1943.976074  1763.994995     FWD   80.0   
3236     Manchester Utd       1.0  1943.976074  1877.037842     FWD   80.0   
3250   Sheffield United       1.0  1943.976074  1637.473755     FWD   80.0   
3249           Brighton       1.0  1943.976074  1832.364258     FWD   80.0   
3225           West Ham       1.0  1943.976074  1777.551270     FWD   80.0   

           Pred  
9323   8.841724  
9325   8.841724  
9346   8.841724  
9320   8.841724  
9335   8.841724  
9327   8.841724  
9330   8.841724  
9350   8.841724  
9341   8.841724  
12267  7.878557  
12283  7.878557  
12274  7.878557  
3221   7.728470  
3257   7.728470  
3255   7.728470  
3252   7.728470  
3236   7.728470  
3250   7.728470  
3249   7.728470  
3225   7.728470

In [28]:
# points all season
pd.DataFrame(preds.groupby(["Name_original"])["Pred"].sum().sort_values(ascending=False)).head(30)

Pred
Name_original                        
Diogo Teixeira da Silva    258.620880
Julián Álvarez             256.045471
Folarin Balogun            229.656647
Kai Havertz                221.007843
Anthony Martial            217.455536
Danny Welbeck              210.814545
Eddie Nketiah              204.299179
Alexander Isak             202.970825
Bryan Mbeumo               200.288620
Julio Enciso               189.234070
Callum Wilson              188.431473
Michail Antonio            184.134613
Mohamed Salah              164.830978
Evan Ferguson              164.142899
Danny Ings                 162.165497
Ollie Watkins              156.280334
Bruno Borges Fernandes     147.516891
Gabriel Martinelli Silva   144.295425
Odsonne Edouard            141.638626
Kieran Trippier            140.628464
Richarlison de Andrade     140.492905
Martin Ødegaard            139.671631
Antony Matheus dos Santos  137.874893
Erling Haaland             136.980087
Marcus Rashford            135.251862
Leandro Trossard           134.266144
William Saliba             130.884995
Benjamin White             130.496231
Kurt Zouma                 127.432640
Kevin De Bruyne            127.257469

# Saving to file

In [29]:
preds.to_csv("predictions/preds_next_season.csv", index=False)