# Imports & setup

In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import pandas as pd
import numpy as np
import pickle
from xgboost import XGBRegressor
from src.PositionalModel import PositionalModel

In [3]:
features = ['Was_home',
 'Rating_difference',
 'Min_2',
 'Gls_2',
 'Ast_2',
 'xG_2',
 'xA_2',
 'Team_CS_2',
 'Team_score_2',
 'Opp_score_2',
 'Team_result_2',
 'FPL_points_2',
 'Min_4',
 'Gls_4',
 'Ast_4',
 'xG_4',
 'xA_4',
 'Team_CS_4',
 'Team_score_4',
 'Opp_score_4',
 'Team_result_4',
 'FPL_points_4',
 'Min_30',
 'Gls_30',
 'Ast_30',
 'xG_30',
 'xA_30',
 'Team_CS_30',
 'Team_score_30',
 'Opp_score_30',
 'Team_result_30',
 'FPL_points_30',
 'DEF',
 'FWD',
 'MID']

info = ["Name_original", "GW", "Season", "Team", "Opponent", "Was_home", "Team_rating", "Opp_rating", "FPL_pos", "Price"]
to_predict = ["FPL_points"]

In [4]:
len(features)

35

# Reading from files

In [5]:
df = pd.read_csv("data/upcoming/upcoming_fixtures.csv")
CURRENT_SEASON = "2023-24"

C:\users\user\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (2,3,6,8,36,43,44,45,59,84,86,147,208) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
df.shape

(35410, 274)

In [7]:
# df = df[df["GW"] == 2]

In [8]:
# X_test = df[df["Season"] == CURRENT_SEASON][features]
df = df[df["Season"] == CURRENT_SEASON]
# .reset_index(drop=True)

In [9]:
df = df[~df[features].isnull().any(axis=1)] # for some reason 45 rows are missing some feature values

In [10]:
X_test = df.copy()

In [11]:
df.columns

Index(['Unnamed: 0', 'Date', 'Day', 'Venue', 'Team', 'Opponent', 'Name',
       'Start', 'Pos', 'Min',
       ...
       'FPL_xGC_30', 'Opp_rating_30', 'Team_rating_30', 'Min_points_30',
       'Team_result_30', 'DEF', 'FWD', 'MID', 'Finished', 'Price'],
      dtype='object', length=274)

In [12]:
file = open("models/GBR_positional.pkl",'rb')
model = pickle.load(file)

In [13]:
model

In [14]:
model.predict( X_test.head(5) )

array([2.12722155, 1.72776586, 1.40875402, 2.63081082, 2.63081082])

In [15]:
model.predict( X_test.head(3) )

array([2.12722155, 1.72776586, 1.40875402])

In [16]:
model.predict( X_test.head(4) )

array([2.12722155, 1.72776586, 1.40875402, 2.63081082])

In [17]:
X_test.head(5)

Unnamed: 0        Date  Day Venue       Team         Opponent  \
76           76  2023-08-20  Sun  Home   West Ham          Chelsea   
105         105  2023-08-13  Sun  Home  Brentford        Tottenham   
106         106  2023-08-19  Sat  Away  Brentford           Fulham   
181         181  2023-08-12  Sat  Home    Arsenal  Nott'ham Forest   
182         182  2023-08-21  Mon  Away    Arsenal   Crystal Palace   

                Name  Start Pos   Min  ...  FPL_xGC_30  Opp_rating_30  \
76   Aaron-Cresswell    0.0   0   0.0  ...        1.02    1777.369124   
105     Aaron-Hickey    1.0  RB  71.0  ...        1.02    1773.661765   
106     Aaron-Hickey    1.0  RB  77.0  ...        1.02    1775.117339   
181   Aaron-Ramsdale    1.0  GK  90.0  ...        1.18    1780.652535   
182   Aaron-Ramsdale    1.0  GK  90.0  ...        1.18    1770.298556   

     Team_rating_30  Min_points_30  Team_result_30  DEF  FWD  MID  Finished  \
76      1761.774146            NaN        1.166667  1.0  0.0  0.0      True   
105     1765.611943            NaN        1.428571  1.0  0.0  0.0      True   
106     1767.636719            NaN        1.413793  1.0  0.0  0.0      True   
181     1925.740381            NaN        2.100000  0.0  0.0  0.0      True   
182     1926.720374            NaN        2.100000  0.0  0.0  0.0      True   

     Price  
76     NaN  
105    NaN  
106    NaN  
181    NaN  
182    NaN  

[5 rows x 274 columns]

In [18]:
X_test.head(3)

Unnamed: 0        Date  Day Venue       Team   Opponent             Name  \
76           76  2023-08-20  Sun  Home   West Ham    Chelsea  Aaron-Cresswell   
105         105  2023-08-13  Sun  Home  Brentford  Tottenham     Aaron-Hickey   
106         106  2023-08-19  Sat  Away  Brentford     Fulham     Aaron-Hickey   

     Start Pos   Min  ...  FPL_xGC_30  Opp_rating_30  Team_rating_30  \
76     0.0   0   0.0  ...        1.02    1777.369124     1761.774146   
105    1.0  RB  71.0  ...        1.02    1773.661765     1765.611943   
106    1.0  RB  77.0  ...        1.02    1775.117339     1767.636719   

     Min_points_30  Team_result_30  DEF  FWD  MID  Finished  Price  
76             NaN        1.166667  1.0  0.0  0.0      True    NaN  
105            NaN        1.428571  1.0  0.0  0.0      True    NaN  
106            NaN        1.413793  1.0  0.0  0.0      True    NaN  

[3 rows x 274 columns]

In [19]:
X_test.head(3)[features]

Was_home  Rating_difference  Min_2  Gls_2  Ast_2  xG_2  xA_2  Team_CS_2  \
76        1.0           0.992481   35.0    0.0    0.0   0.0  0.00        0.0   
105       1.0           1.004657   78.5    0.0    0.5   0.0  0.05        0.5   
106       0.0           1.044221   70.0    0.0    0.0   0.0  0.05        0.5   

     Team_score_2  Opp_score_2  ...     xG_30     xA_30  Team_CS_30  \
76            2.0          1.5  ...  0.000000  0.096667    0.266667   
105           2.0          0.5  ...  0.007143  0.010714    0.285714   
106           1.5          1.0  ...  0.006897  0.013793    0.275862   

     Team_score_30  Opp_score_30  Team_result_30  FPL_points_30  DEF  FWD  MID  
76        1.266667      1.500000        1.166667       2.033333  1.0  0.0  0.0  
105       1.500000      1.250000        1.428571       2.107143  1.0  0.0  0.0  
106       1.517241      1.275862        1.413793       2.034483  1.0  0.0  0.0  

[3 rows x 35 columns]

# Predicting

In [20]:
def adjust_for_injuries(df):
    active_players = pd.read_csv("data/misc/active_players.csv")
    injured_players = active_players[active_players["chance_of_playing_this_round"] == 0]["name"].to_list()
    df.loc[df["Name_original"].isin(injured_players),"Pred"] = 0
    return df

In [21]:
def adjust_goalkeepers(df):
    gks = pd.read_csv("data/misc/goalkeepers.csv")
    gk_names = gks["Name"].to_list()
    gk_names = [name_fbref_to_fpl(neutralize_name(n)) for n in gk_names]
    # print(gk_names)
    df.loc[(df["FPL_pos"] == "GK") & ~(df["Name_original"].apply(neutralize_name).isin(gk_names)), "Pred"] = 0
    return df

In [22]:
def get_predictions(model, df, X):
    # make predictions on the test data and glues them to the rest of the dataframe
    predictions = model.predict(X)
    
    df_predictions = df[(df["Season"] == CURRENT_SEASON)].reset_index(drop=True)
        
    print(len(predictions), df_predictions.shape)
        
    df_predictions.loc[:, "Pred"] = predictions
    preds = df_predictions[info + ["Pred"]]
    
    preds = adjust_goalkeepers(preds)
    preds = adjust_for_injuries(preds).sort_values(by=["Pred"], ascending = False)
    
    return preds

In [23]:
X_test[features].isna()

Was_home  Rating_difference  Min_2  Gls_2  Ast_2   xG_2   xA_2  \
76        False              False  False  False  False  False  False   
105       False              False  False  False  False  False  False   
106       False              False  False  False  False  False  False   
181       False              False  False  False  False  False  False   
182       False              False  False  False  False  False  False   
...         ...                ...    ...    ...    ...    ...    ...   
35405     False              False  False  False  False  False  False   
35406     False              False  False  False  False  False  False   
35407     False              False  False  False  False  False  False   
35408     False              False  False  False  False  False  False   
35409     False              False  False  False  False  False  False   

       Team_CS_2  Team_score_2  Opp_score_2  ...  xG_30  xA_30  Team_CS_30  \
76         False         False        False  ...  False  False       False   
105        False         False        False  ...  False  False       False   
106        False         False        False  ...  False  False       False   
181        False         False        False  ...  False  False       False   
182        False         False        False  ...  False  False       False   
...          ...           ...          ...  ...    ...    ...         ...   
35405      False         False        False  ...  False  False       False   
35406      False         False        False  ...  False  False       False   
35407      False         False        False  ...  False  False       False   
35408      False         False        False  ...  False  False       False   
35409      False         False        False  ...  False  False       False   

       Team_score_30  Opp_score_30  Team_result_30  FPL_points_30    DEF  \
76             False         False           False          False  False   
105            False         False           False          False  False   
106            False         False           False          False  False   
181            False         False           False          False  False   
182            False         False           False          False  False   
...              ...           ...             ...            ...    ...   
35405          False         False           False          False  False   
35406          False         False           False          False  False   
35407          False         False           False          False  False   
35408          False         False           False          False  False   
35409          False         False           False          False  False   

         FWD    MID  
76     False  False  
105    False  False  
106    False  False  
181    False  False  
182    False  False  
...      ...    ...  
35405  False  False  
35406  False  False  
35407  False  False  
35408  False  False  
35409  False  False  

[16262 rows x 35 columns]

In [24]:
# X_test.shape,  model.predict(X_test).shape

In [25]:
%%time
preds = get_predictions(model, df, X_test)

16262 (16262, 274)


NameError: name 'name_fbref_to_fpl' is not defined

In [26]:
# preds[(preds["FPL_pos"] == "GK") & (preds["GW"] == 2)].head(30)

In [27]:
# next gameweek
preds[preds["GW"] == 3].head(50)

NameError: name 'preds' is not defined

In [ ]:
# all preds
preds.head(20)

In [ ]:
preds[preds["FPL_pos"] == "GK"].head(20)

In [ ]:
# points all season
pd.DataFrame(preds.groupby(["Name_original"])["Pred"].sum().sort_values(ascending=False)).head(30)

# Saving to file

In [ ]:
preds.to_csv("predictions/preds_next_season.csv", index=False)